version: '3.8'
services:
  gateway:
    build: gateway
    image: gateway
    container_name: shareit-gateway
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: server
    image: server
    container_name: shareit-server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/ShareItDb
      - SPRING_DATASOURCE_USERNAME=ShareItDbAdmin
      - SPRING_DATASOURCE_PASSWORD=admin

  db:
    image: postgres:14-alpine
    container_name: shareit-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ShareItDb
      - POSTGRES_USER=ShareItDbAdmin
      - POSTGRES_PASSWORD=admin